"""questions table users table

Revision ID: 20c4c62b4057
Revises: 68e4e904097b
Create Date: 2019-08-16 23:35:27.934500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c4c62b4057'
down_revision = '68e4e904097b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_key', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answer_key', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer_key', type_='foreignkey')
    op.drop_column('answer_key', 'question_id')
    # ### end Alembic commands ###
