"""empty message

Revision ID: 68e4e904097b
Revises: 8c1067cc957a
Create Date: 2019-08-16 23:34:16.785725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e4e904097b'
down_revision = '8c1067cc957a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=1200), nullable=True),
    sa.Column('optionA', sa.String(length=200), nullable=True),
    sa.Column('optionB', sa.String(length=200), nullable=True),
    sa.Column('optionC', sa.String(length=200), nullable=True),
    sa.Column('optionD', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('answer_key')
    # ### end Alembic commands ###
